version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend  # Указываем Dockerfile для бэкенда
    ports:
      - "5000:5000"  # Пробрасываем порт для бэкенда
    volumes:
      - ./backend:/app/backend   # Привязываем папку с бэкендом для разработки
      - ./run.py:/app/run.py     # Привязываем run.py для запуска
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    networks:
      - app_network

  frontend:
    build:
      context: ./todo_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./todo_frontend:/todo_frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
