
FROM python:3.10-slim

WORKDIR /app

COPY ./backend /app/backend
COPY ./run.py /app/
COPY ./requirements.txt /app/requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn


EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:run"]
