FROM python:3.11-slim

WORKDIR /app

# Копируем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем все файлы проекта
COPY . .

# Устанавливаем переменные окружения для Flask
ENV FLASK_APP=run.py
ENV FLASK_ENV=production

# Устанавливаем gunicorn
RUN pip install gunicorn

# Команда для запуска через gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:5000", "run:app"]
